# Generated by Django 1.9.13 on 2017-08-08 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcm_django", "0004_auto_20181128_1642"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcmdevice",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.FCM_DJANGO_SETTINGS["USER_MODEL"],
            ),
        ),
    ]
